services:
  postgres:
    image: postgres:16
    container_name: Database
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d

  my-server:
    image: node:24
    container_name: Backend
    working_dir: /app
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev"
    env_file:
      - .env
    environment:
      NODE_ENV: development

volumes:
  postgres_data:
